try {
    #Check log size does not exceed 4 MB
    if ((get-item "C:\windows\temp\dnsfix.log").Length /1MB -ge 4) { 
        "*** Log file auto-cleared on $(get-date)" |out-file "C:\windows\temp\dnsfix.log" 
    }
} catch {
    #Error. No Action required.
}

Start-Transcript -Path "C:\windows\temp\dnsfix.log" -append

$RegisterDNS = $false
$dnsServerIP = "10.20.248.245"


$DNSreachable = test-connection $dnsServerIP -Count 1 -quiet
if ($DNSreachable ) {

    $nics=Get-WmiObject "Win32_NetworkAdapterConfiguration where IPEnabled='TRUE'"
    $VPN_nic = $nics |where {$_.ServiceName -eq "vpnva" -or $_.ServiceName -eq "Netwtw12"}

    if (  $VPN_nic -ne $null ) {
        #VPN adapter is active
        #Enable DNS Registration for VPN virtual adapter and disable for all others
        write-host "VPN Adapter is active $($VPN_nic.description) with IP $($VPN_nic.IPAddress)"
        foreach($nic in $nics)
            {
                write-host "Configuring $($nic.description) with IP $($nic.IPAddress)"

                if( $nic.ServiceName -eq "vpnva" ) {
                    Write-host "Detected as VPN. Enabling DNS registration for this adapter"
                    $nic.SetDynamicDNSRegistration($true)
             

                } else {
                 Write-host "Detected as NOT VPN. Disabling DNS registration for this adapter"
                    $nic.SetDynamicDNSRegistration($false)
                }

            }

    } else {
            #VPN is not active, enable all interfaces
            write-host "VPN Adapter Not detected"
            foreach($nic in $nics)
            {       
                    write-host "Configuring $($nic.description) with IP $($nic.IPAddress). Enabling DNS registration for this adapter"
                    $nic.SetDynamicDNSRegistration($true)
            }

    }

    $myfqdn = $(hostname)+".folknet.intern.folksam.se"
    $QueryMyIPs = Resolve-DnsName -Name $myfqdn -Server $dnsServerIP -Type A -DnsOnly
    write-host "Query DNS for $myfqdn type A records:"
    $QueryMyIPs |ft
    if ($QueryMyIPs.count -gt 1 ) {
        Write-Host "More than one entry found in DNS. Registration will be triggered"
        ipconfig /registerdns
        #Flush DNS local Cache
        write-host "Running ipconfig /flushdns (Flush local DNS cache)"
        ipconfig /flushdns
    } else {
        Write-Host "No multiple entries found in DNS. Registration not required"
    }
} else {
    Write-Host "DNS $dnsServerIP not reachable. Nothing to do"
}

Stop-Transcript

# SIG # Begin signature block
# MIIShwYJKoZIhvcNAQcCoIISeDCCEnQCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU3Ak7AjeBukbENZ11hawmisT6
# g0Sggg+9MIIHgzCCBmugAwIBAgITTgAAEFwXZQOuZg2jFwAAAAAQXDANBgkqhkiG
# 9w0BAQsFADB7MRIwEAYKCZImiZPyLGQBGRYCc2UxFzAVBgoJkiaJk/IsZAEZFgdm
# b2xrc2FtMRYwFAYKCZImiZPyLGQBGRYGaW50ZXJuMRcwFQYKCZImiZPyLGQBGRYH
# Zm9sa25ldDEbMBkGA1UEAxMSRm9sa3NhbS1Jc3N1aW5nQ0EyMB4XDTIwMDExNDE1
# MzY1OFoXDTIyMDExMzE1MzY1OFowFjEUMBIGA1UEAwwLU1ZDX2NlcnRfY3MwggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDbrdaCDdI3WCCwW7Lcq9EJOcS8
# UwGsAl1zMVghHv5b6u1hk8h63lFMBXlPQBVNY+L8MVtXeOlEOTEppCRJ5lQxXuBT
# +hb+Z+wHzq0+a9zbmUA4QYDaGdf8akT53FmI/FDpaEmGBI55Im3f3sb7Q7vXlYxT
# 7J5GVcL6hzJ/s/BBct6k/QIC0MbEKLLrXxI1XwcjbcMTSZGkIft2p6FPPphuQvZj
# iBKoZAFoYhoTHfVPCjOzIHXN2v4NMuWl575rLUXQrGhZC4DDSOmWLCk+C8JrAv4s
# Of6H2sc9U+KCmninfZQfmHZvn+e2SFRaixJkPnnYqjujaPtwMh5/Si9fQaEdAgMB
# AAGjggRjMIIEXzA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiF29sbgpmWe4aZ
# jzCmjE+GyJIDgVKCzehKhvHwBQIBZAIBITATBgNVHSUEDDAKBggrBgEFBQcDAzAL
# BgNVHQ8EBAMCB4AwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4E
# FgQUH/jHaxik3VY1NMCjrNsLivV3RccwHwYDVR0jBBgwFoAU6C0spo0zqTc/MMwY
# cAPZZyY92mwwggGDBgNVHR8EggF6MIIBdjCCAXKgggFuoIIBaoaB0WxkYXA6Ly8v
# Q049Rm9sa3NhbS1Jc3N1aW5nQ0EyLENOPXNmY2l3cHBraTAyLENOPUNEUCxDTj1Q
# dWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0
# aW9uLERDPWZvbGtuZXQsREM9aW50ZXJuLERDPWZvbGtzYW0sREM9c2U/Y2VydGlm
# aWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1
# dGlvblBvaW50hklodHRwOi8vcGtpY2ExLmZvbGtuZXQuaW50ZXJuLmZvbGtzYW0u
# c2UvQ2VydEVucm9sbC9Gb2xrc2FtLUlzc3VpbmdDQTIuY3JshklodHRwOi8vcGtp
# Y2EyLmZvbGtuZXQuaW50ZXJuLmZvbGtzYW0uc2UvQ2VydEVucm9sbC9Gb2xrc2Ft
# LUlzc3VpbmdDQTIuY3JsMIIB1AYIKwYBBQUHAQEEggHGMIIBwjCBxQYIKwYBBQUH
# MAKGgbhsZGFwOi8vL0NOPUZvbGtzYW0tSXNzdWluZ0NBMixDTj1BSUEsQ049UHVi
# bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
# bixEQz1mb2xrbmV0LERDPWludGVybixEQz1mb2xrc2FtLERDPXNlP2NBQ2VydGlm
# aWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MHsG
# CCsGAQUFBzAChm9odHRwOi8vcGtpY2ExLmZvbGtuZXQuaW50ZXJuLmZvbGtzYW0u
# c2UvQ2VydEVucm9sbC9zZmNpd3Bwa2kwMi5mb2xrbmV0LmludGVybi5mb2xrc2Ft
# LnNlX0ZvbGtzYW0tSXNzdWluZ0NBMi5jcnQwewYIKwYBBQUHMAKGb2h0dHA6Ly9w
# a2ljYTIuZm9sa25ldC5pbnRlcm4uZm9sa3NhbS5zZS9DZXJ0RW5yb2xsL3NmY2l3
# cHBraTAyLmZvbGtuZXQuaW50ZXJuLmZvbGtzYW0uc2VfRm9sa3NhbS1Jc3N1aW5n
# Q0EyLmNydDBABgNVHREEOTA3oDUGCisGAQQBgjcUAgOgJwwlU1ZDX2NlcnRfY3NA
# Zm9sa25ldC5pbnRlcm4uZm9sa3NhbS5zZTANBgkqhkiG9w0BAQsFAAOCAQEAE1QX
# AxL7u6yQsuW+znVBYt2sbOo8FW7/XfqVRsq0pv1/K7ULoSfF3ZEkWWSWP/5E0vBD
# tLktA0dh7ilRsQvghhV0NaHpmQZNk4A2XouXX09OSJLL120+/y6dUqem7hmzZiyx
# BGDjLYpyhJmwFOp5W8rGku0Ikp36oY6U3vWAzkxA6VTIcZk/JzLDla/fuHbKBnxd
# WgRkuhDs/1lZ46CCJWoGhqhASAh4lsqlrIka2XzDTgJuQvcwcEYqvqdwAPBeoScQ
# xCkur4zyRkj3x1ZVR5BH+6uHZjF6gBd9GDvDV8PqqJn1FX6SFhIp0ufpSK0rZShE
# U96R9zomQoizEtKn8jCCCDIwggYaoAMCAQICE2sAAAAL7gvlAUYSN1oAAAAAAAsw
# DQYJKoZIhvcNAQELBQAwGTEXMBUGA1UEAxMORm9sa3NhbS1Sb290Q0EwHhcNMTkw
# MTAyMTExOTM2WhcNMjkwMTAyMTEyOTM2WjB7MRIwEAYKCZImiZPyLGQBGRYCc2Ux
# FzAVBgoJkiaJk/IsZAEZFgdmb2xrc2FtMRYwFAYKCZImiZPyLGQBGRYGaW50ZXJu
# MRcwFQYKCZImiZPyLGQBGRYHZm9sa25ldDEbMBkGA1UEAxMSRm9sa3NhbS1Jc3N1
# aW5nQ0EyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1tWKKzWO/9Yf
# JGImMVT5LZYtvaQGaQK/gmx6mAL4PnRSNx/0AxpR6bWL7sLYBtAMgmcJ0de5NIgm
# B/o8Fo4AyXG7EwHnaHhv2NbRlkIbqf0RKWmCZ2esS9q9YqPlDiwrjYeTpk8rTn7z
# GfbV5VmE6Vg6eZC3+Z+yK2FlL5aOKmA/UEhPnoTySYU7uKFztoFpCi/IwAsD0o9i
# 5L4Ab9eMLZlaQfWEBSAxx62lJwV4W1L3mrAJnFy6eqV7FfkaArgSTBNTDH85K9HN
# C9O/uWMIAFVES5q7IpPjC9+kCM56PrCd/jWf2DGae0iSJefgPFlL7i/qaSTBB4mf
# otmaD4P++QIDAQABo4IEDzCCBAswEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYE
# FOgtLKaNM6k3PzDMGHAD2WcmPdpsMF8GA1UdIARYMFYwVAYIKgMEiy9DWQUwSDBG
# BggrBgEFBQcCARY6aHR0cDovL3BraWNhMi5mb2xrbmV0LmludGVybi5mb2xrc2Ft
# LnNlL0NlcnRFbnJvbGwvY3BzLnR4dDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMA
# QTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRzFPIV
# RYF6DsEDv44fGyZjEg9k3jCCAXsGA1UdHwSCAXIwggFuMIIBaqCCAWagggFihoHR
# bGRhcDovLy9DTj1Gb2xrc2FtLVJvb3RDQSxDTj1XSU4tTlVCNk9PUzQxMlAsQ049
# Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNv
# bmZpZ3VyYXRpb24sREM9Zm9sa25ldCxEQz1pbnRlcm4sREM9Zm9sa3NhbSxEQz1z
# ZT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JM
# RGlzdHJpYnV0aW9uUG9pbnSGRWh0dHA6Ly9wa2ljYTEuZm9sa25ldC5pbnRlcm4u
# Zm9sa3NhbS5zZS9DZXJ0RW5yb2xsL0ZvbGtzYW0tUm9vdENBLmNybIZFaHR0cDov
# L3BraWNhMi5mb2xrbmV0LmludGVybi5mb2xrc2FtLnNlL0NlcnRFbnJvbGwvRm9s
# a3NhbS1Sb290Q0EuY3JsMIIBnAYIKwYBBQUHAQEEggGOMIIBijCBwQYIKwYBBQUH
# MAKGgbRsZGFwOi8vL0NOPUZvbGtzYW0tUm9vdENBLENOPUFJQSxDTj1QdWJsaWMl
# MjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
# PWZvbGtuZXQsREM9aW50ZXJuLERDPWZvbGtzYW0sREM9c2U/Y0FDZXJ0aWZpY2F0
# ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwYQYIKwYB
# BQUHMAKGVWh0dHA6Ly9wa2ljYTEuZm9sa25ldC5pbnRlcm4uZm9sa3NhbS5zZS9D
# ZXJ0RW5yb2xsL1dJTi1OVUI2T09TNDEyUF9Gb2xrc2FtLVJvb3RDQS5jcnQwYQYI
# KwYBBQUHMAKGVWh0dHA6Ly9wa2ljYTIuZm9sa25ldC5pbnRlcm4uZm9sa3NhbS5z
# ZS9DZXJ0RW5yb2xsL1dJTi1OVUI2T09TNDEyUF9Gb2xrc2FtLVJvb3RDQS5jcnQw
# DQYJKoZIhvcNAQELBQADggIBADIGIP+qu/pKcAhkSqCytrTDmLPEoBX0beRIg9O9
# +hqGzp7KGf5QfZ82SNPgqW4fZa9XbeIt7AyKJzRwmLhy6Hb9jc8xGy9kdXu7obXe
# 80X6DhnWmv1E/sUzSi3/kjhTCN7f1FNQGfeSiph0Hltm9rLQOIKOaqfvaPN4pIZ0
# 5vYPXOjMy1m2e71P6+3Y/A6JSQDDOhrXL7oXTwV3bz8WfWcDsTNxogxlTq0rU7ti
# 6CKXQXuIsQHq0mgnByiRwLoudmWWTOn3vmYfNkCzK5XGfYoFn6+ldp1QN6gQf/gq
# HnI3GgPy0JV+4W0csZuoyHqDPAw5vd/ktrlAGwvuEPY98IUiDPVqj1D8ALy8Micl
# aQiBPBhV10IF2Ia+5SpNf816WLpRsM8YQTGXZ3Qi2KwZ4JEMmk19qehlwZHAxNbj
# 2bfQoa/1zFBPPEKUtToNMEqJ8XdSwXz1PVXY9v7XhL6CId64TyiqYnXLo61HQ/KD
# 74F0h3zx5uE8yiFZoe0WmTuZVcVZUjU9si9D2m4OSvd9a1HPBn/UYOwl9+79oY0b
# +L7xzlQwf0fsuJxmXzFh3FG9up2vBJzYu1OgeVDaLgpEAaYiLgali3F5PICpyQtl
# IcCY7cILVqnoAyD2180D7dLd7edCYzvYUP1sOPS7lqECVl6BOdx+8sTBnJM0QDC3
# tqI6MYICNDCCAjACAQEwgZIwezESMBAGCgmSJomT8ixkARkWAnNlMRcwFQYKCZIm
# iZPyLGQBGRYHZm9sa3NhbTEWMBQGCgmSJomT8ixkARkWBmludGVybjEXMBUGCgmS
# JomT8ixkARkWB2ZvbGtuZXQxGzAZBgNVBAMTEkZvbGtzYW0tSXNzdWluZ0NBMgIT
# TgAAEFwXZQOuZg2jFwAAAAAQXDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEK
# MAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3
# AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUNc//IDuO+OL2HR3Q
# odE4179k8b0wDQYJKoZIhvcNAQEBBQAEggEAeX1mHBasjSi329lksk0lb58OpfIO
# je3FYBnxf1Lsv7ofsCCylCQSk+htTj/inuPRgkx+dkEGsN5lzwapVj176C0u9j5Z
# U+L4qT2YYgTCGBY5a4nToZF2MYWKBGAYyWJRI+MVlyotcR7frQ0U77RqEHXnweWP
# ESDNd+pxpZw0O92gqe7rdJ6fNkzwt882BrWIeyZhdNn/fwxv5TYpwZZh7wQgpL4c
# 7fzJj4aFQsBjRjdo/3qJjsyFulyD61i/PoDnNHV8K3H3dp7XKW9bSSkGI5djMuu8
# khuV8c8kGqunWPTVsOKoJEJl84qqdpcMsFrhn6zcqmk/e6Vq/+Pa/AU2sw== C:\Windows\System32\Tasks
# SIG # End signature block


Get-MessageTrackingLog -Sender "ylva.wessen@folksam.se" -MessageSubject "Sv: Exclusive preview of Liljevalchs Vårsalong - Feb 7th 2024","ylva.wessen@folksam.se" -Start "2024/11/1" -End "2024/11/15" | Select-Object Timestamp, Sender, Recipients, MessageSubject
Get-Mailbox -Identity "SWEP280A002.PROD.OUTLOOK.COM" 
Get-DistributionGroup -Identity "Liljevalchs" | Format-List
a14676b4-d37d-4635-a90d-273ec7fe2025

https://graph.microsoft.com/v1.0/groups/e3774875-9428-4743-8a2d-4efc39e334c0/members/$select=Email


https://graph.microsoft.com/v1.0/groups/e3774875-9428-4743-8a2d-4efc39e334c0/members/microsoft.graph.user?$count=true&$orderby=displayName&$select="User princripal name"
ConsistencyLevel: eventual


GET https://graph.microsoft.com/v1.0/groups/e3774875-9428-4743-8a2d-4efc39e334c0/members/microsoft.graph.user?$count=true&$orderby=displayName&$select=displayName,id
ConsistencyLevel: eventual

Get-AzureADObjectByObjectId -ObjectIds 714726a5-4440-4f63-9df9-607b1c0c8a1b
714726a5-4440-4f63-9df9-607b1c0c8a1b

714726a5-4440-4f63-9df9-607b1c0c8a1b

Import-Module Microsoft.Graph.Groups

Get-MgGroupMemberOf -GroupId $groupId

GET /groups/{id}/memberOf

GET /groups/{id}/members

GET https://graph.microsoft.com/v1.0/groups/e3774875-9428-4743-8a2d-4efc39e334c0/members

https://graph.microsoft.com/v1.0/groups/e3774875-9428-4743-8a2d-4efc39e334c0/members?$count=true

git remote add upstream https://git-tos.intern.folksam.se/s88/docker-teamspeak

glagent-VYSm8fMVto_xJx3eDagoVs3socnAu3hUx_Cip2scyxstao52fg

helm repo add gitlab https://charts.gitlab.io
helm repo update
helm upgrade --install s88 gitlab/gitlab-agent \
    --namespace gitlab-agent-s88 \
    --create-namespace \
    --set image.tag=v16.9.0-rc1 \
    --set config.token=glagent-VYSm8fMVto_xJx3eDagoVs3socnAu3hUx_Cip2scyxstao52fg \
    --set config.kasAddress=wss://git-tos.intern.folksam.se/-/kubernetes-agent/


    select FAKTA_KUNDKONTAKT_AGENT_DAG.AGENT_DIMID, FAKTA_KUNDKONTAKT_DAG.KONTAKTDATUM_DIMID Period , FAKTA_KUNDKONTAKT_DAG.KOSTNADSSTALLE_DD
Kst , FAKTA_KUNDKONTAKT_DAG.INKOMNA_ARENDEN INKOMNA_ARENDEN , FAKTA_KUNDKONTAKT_DAG.KORTA_OVERGIVNA
KORTA_OVERGIVNA , FAKTA_KUNDKONTAKT_DAG.BESVARADE_TALSVARSSAMTAL BESVARADE_TALSVARSSAMTAL
, FAKTA_KUNDKONTAKT_DAG.KORREKT_AVSL_TALSVARSSAMTAL c6 , FAKTA_KUNDKONTAKT_DAG.BESV_TALSVARSSAMTAL_INOM_SN1
c7 , FAKTA_KUNDKONTAKT_DAG.AVSLUTADE_CALLBACK AVSLUTADE_CALLBACK , FAKTA_KUNDKONTAKT_DAG.VARAV_KORREKT_AVSL_CALLBACK
c9 , FAKTA_KUNDKONTAKT_DAG.RINGDA_CALLBACK_INOM_SN1 RINGDA_CALLBACK_INOM_SN1
, FAKTA_KUNDKONTAKT_DAG.FORLORADE_ARENDEN FORLORADE_ARENDEN , FAKTA_KUNDKONTAKT_DAG.ARENDETID_TALSVARSSAMTAL
ARENDETID_TALSVARSSAMTAL , FAKTA_KUNDKONTAKT_DAG.ARENDETID_CALLBACK ARENDETID_CALLBACK
, FAKTA_KUNDKONTAKT_DAG.INKOMNA_E_BREV INKOMNA_E_BREV , FAKTA_KUNDKONTAKT_DAG.BESVARADE_E_BREV_INOM_SN1
BESVARADE_E_BREV_INOM_SN1 , FAKTA_KUNDKONTAKT_DAG.AVSLUTADE_E_BREV AVSLUTADE_E_BREV
, FAKTA_KUNDKONTAKT_DAG.AVBRUTNA_E_BREV AVBRUTNA_E_BREV , FAKTA_KUNDKONTAKT_DAG.ARENDETID_E_BREV
ARENDETID_E_BREV , FAKTA_KUNDKONTAKT_DAG.TOTAL_HANDLAGGNINGSTID TOTAL_HANDLAGGNINGSTID
, DIM_ARENDE.ARENDE_KOD ARENDE_KOD , DIM_ARENDE.ARENDE_BESKR_AKTUELL ARENDE_BESKR_AKTUELL
, DIM_TIDSINTERVALL.START_TIDSINTERVALL START_TIDSINTERVALL , DIM_TIDSINTERVALL.SLUT_TIDSINTERVALL
SLUT_TIDSINTERVALL , substring (DIM_TIDSINTERVALL.START_TIDSINTERVALL
from
1 for 5) || ' - ' || substring (DIM_TIDSINTERVALL.SLUT_TIDSINTERVALL
from 1
for 5) Tidfrantxt , FAKTA_KUNDKONTAKT_DAG.INKOMNA_CHATTAR INKOMNA_CHATTAR
, FAKTA_KUNDKONTAKT_DAG.BESV_CHATTAR_INOM_SN1 BESV_CHATTAR_INOM_SN1 , FAKTA_KUNDKONTAKT_DAG.BESVARADE_CHATTAR
BESVARADE_CHATTAR , FAKTA_KUNDKONTAKT_DAG.AVSLUTADE_CHATTAR AVSLUTADE_CHATTAR
, FAKTA_KUNDKONTAKT_DAG.EJ_KORRKT_AVSL_CHATTAR EJ_KORRKT_AVSL_CHATTAR , FAKTA_KUNDKONTAKT_DAG.ARENDETID_CHATTAR
ARENDETID_CHATTAR , FAKTA_KUNDKONTAKT_DAG.TOTAL_VANTETID_BESV_CHATTAR TOTAL_VANTETID_BESV_CHATTAR
, FAKTA_KUNDKONTAKT_DAG.OVERGIVNA_1 OVERGIVNA_1 , FAKTA_KUNDKONTAKT_DAG.OVERGIVNA_2
OVERGIVNA_2 , FAKTA_KUNDKONTAKT_DAG.OVERGIVNA_3 OVERGIVNA_3 , FAKTA_KUNDKONTAKT_DAG.OVERGIVNA_4
OVERGIVNA_4 , FAKTA_KUNDKONTAKT_DAG.MEDEL_SVARSTID MEDEL_SVARSTID 
from
QDPG70AN.SG70KONTAKTCENTER.FAKTA_KUNDKONTAKT_DAG FAKTA_KUNDKONTAKT_DAG, QDPG70AN.SG70KONTAKTCENTER.DIM_ARENDE
DIM_ARENDE, QDPG70AN.SG70KONTAKTCENTER.DIM_TIDSINTERVALL DIM_TIDSINTERVALL
 
where FAKTA_KUNDKONTAKT_DAG.ARENDE_DIMID = DIM_ARENDE.ARENDE_DIMID and FAKTA_KUNDKONTAKT_DAG.TIDSINTERVALL_DIMID
= DIM_TIDSINTERVALL.TIDSINTERVALL_DIMID

/*SELECT * FROM SG70CONTACTCENTERMART.DIM_WORKLEVEL 

SELECT DIM_AGENT.AGENT_DIMID, DIM_ARENDEARENDE_DIMID, FAKTA_KUNDKONTAKT_AGENT_DAG.ARENDE_DIMID, FAKTA_KUNDKONTAKT_AGENT_DAG.ARENDE_DIMID

FROM SG70KONTAKTCENTER.DIM_AGENT
SG70KONTAKTCENTER.DIM_ARENDE
SG70KONTAKTCENTER.FAKTA_KUNDKONTAKT_AGENT_DAG



FULL OUTER JOIN SG70KONTAKTCENTER.DIM_AKTIVITET
ON SG70KONTAKTCENTER.DIM_AGENT.AGENT_DIMID = SG70KONTAKTCENTER.DIM_AKTIVITET.AKTIVITET_DIMID
WHERE DIM_AGENT.AGENT_RACFID = AKTIVITET_DIMID */


SELECT DIM_AGENT.AGENT_DIMID, DIM_ARENDEARENDE_DIMID, FAKTA_KUNDKONTAKT_AGENT_DAG.ARENDE_DIMID, FAKTA_KUNDKONTAKT_AGENT_DAG.ARENDE_DIMID
FROM SG70KONTAKTCENTER.DIM_AGENT
FULL OUTER JOIN SG70KONTAKTCENTER.FAKTA_KUNDKONTAKT_AGENT_DAG
ON DIM_AGENT.AGENT_DIMID = FAKTA_KUNDKONTAKT_AGENT_DAG.AGENT_DIMID
FULL OUTER JOIN SG70KONTAKTCENTER.FAKTA_KUNDKONTAKT_AGENT_DAG
ON DIM_ARENDE.ARENDE_DIMID = FAKTA_KUNDKONTAKT_AGENT_DAG.ARENDE_DIMID